### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by AdySan** [dmaupin/casabaone#12]
Hello,

I'm pretty new to Ruby on rails. Can I get some simple instructions on how to run this on a mac? I tried googling, but simple pointers like `bundle install` and `rails server` don't seem to work.

**Comment by dmaupin** [comment]
Hi,

This is not a rails app. It was built with Middleman. ( https://middlemanapp.com ) A static site compiler. If you install Middleman you'll be able to run it. It's just a modest single page site. 

Hope that helps.

**Comment by AdySan** [comment]
Thanks, after spending an hour or so I'm giving up on getting middleman to work. For some reason it only installs 3.4.1 not the latest 4.2.1. If you have a built version of this site that I can take a look at please let me know.

Thanks.

Ady
